user:
  photo_format: "image/jpeg,image/gif,image/png"
  name_max_length: 100
  email_max_length: 255
  address_max_length: 255
  phone_max_length: 16
  password_min_length: 6
  password_max_length: 128
  photo_max_size: 2097152
  photo_size_large: 250
  photo_size_small: 50
admin:
  user:
    page_items_limit:
      level1: 5
      level2: 20
      level3: 50
  product:
    prefix_code: "PRD"
show_limit:
  show_8: 8
  show_20: 20
  show_50: 40
period_date: 7
most_like_limit: 6
carousel_photo_size: 300
recent_items_limit: 8
cart:
  item_photo_size: 30
